from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.domain.enums import EvidenceSourceType
from app.domain.value_objects import FiveLevelScale, NormalizedScore


class Evidence(BaseModel):
    """Immutable proof generated by a learning interaction.

    Never edited after creation -- see docs/DOMAIN_MODEL.md #6 and
    docs/AGENTS.md #8 (raw evidence is append-only).
    """

    model_config = ConfigDict(frozen=True)

    id: str
    concept_id: str
    skill_ids: list[str] = Field(default_factory=list)
    goal_id: str
    session_id: str | None = None
    activity_id: str
    source_type: EvidenceSourceType
    difficulty: FiveLevelScale
    correctness: NormalizedScore | None = None
    reasoning: NormalizedScore | None = None
    independence: NormalizedScore | None = None
    transfer: NormalizedScore | None = None
    confidence: NormalizedScore | None = None
    timestamp: datetime
    metadata: dict[str, Any] = Field(default_factory=dict)
