"""add change proposals table

Fixes a gap found while implementing T046: docs/DATABASE_SCHEMA.md never
listed a change_proposals table, despite docs/SPECS.md #16,
docs/AI_CONTRACTS.md #9 and docs/API_SPEC.md #2 (vault changes) all
describing this exact flow (pending/approved/rejected/applied/
conflicted/failed proposals for limited Obsidian write operations).

Revision ID: b9c38d0c7cf0
Revises: 017d17b1666e
Create Date: 2026-09-15 15:13:39.769511

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9c38d0c7cf0"
down_revision: str | None = "017d17b1666e"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_proposals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("section", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("applied_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("change_proposals")
    # ### end Alembic commands ###
