"""domain schema

Creates the 17 tables from docs/DATABASE_SCHEMA.md #2 and their indexes
(#3): goals, concepts(+relations), skills(+concepts), sessions,
activities, exercises(+concepts, attempts), evaluations, evidence,
mistakes, reviews, ai_runs, vault_files.

Revision ID: fd57ee07b3b9
Revises: 815122603aaa
Create Date: 2026-09-15 11:36:52.765292

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd57ee07b3b9"
down_revision: str | None = "815122603aaa"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("input_hash", sa.String(), nullable=True),
        sa.Column("output_schema", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concepts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("retention", sa.Float(), nullable=False),
        sa.Column("last_practiced", sa.String(), nullable=True),
        sa.Column("next_review", sa.String(), nullable=True),
        sa.Column("obsidian_path", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_concepts_next_review", "concepts", ["next_review"], unique=False)
    op.create_table(
        "goals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("target_level", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("deadline", sa.String(), nullable=True),
        sa.Column("available_minutes_per_week", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("mastery", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vault_files",
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("modified_at", sa.String(), nullable=False),
        sa.Column("indexed_at", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("path"),
    )
    op.create_index("idx_vault_files_hash", "vault_files", ["content_hash"], unique=False)
    op.create_table(
        "concept_relations",
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("source_id", "target_id", "relation"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("prompt", sa.String(), nullable=False),
        sa.Column("solution", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goal_concepts",
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("goal_id", "concept_id"),
    )
    op.create_table(
        "mistakes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.String(), nullable=False),
        sa.Column("last_seen", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_mistakes_concept", "mistakes", ["concept_id", "resolved_at"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("scheduled_at", sa.String(), nullable=False),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.Column("interval_days", sa.Float(), nullable=False),
        sa.Column("stability", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reviews_schedule", "reviews", ["scheduled_at", "status"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("objective", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("ended_at", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skill_concepts",
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("skill_id", "concept_id"),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payload_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("submitted_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_concepts",
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_id", "concept_id"),
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("attempt_id", sa.String(), nullable=False),
        sa.Column("correctness", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Float(), nullable=False),
        sa.Column("completeness", sa.Float(), nullable=False),
        sa.Column("independence", sa.Float(), nullable=False),
        sa.Column("transfer", sa.Float(), nullable=False),
        sa.Column("feedback", sa.String(), nullable=False),
        sa.Column("misconceptions_json", sa.String(), nullable=False),
        sa.Column("recommended_action", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["exercise_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal_id", sa.String(), nullable=False),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("correctness", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Float(), nullable=True),
        sa.Column("independence", sa.Float(), nullable=True),
        sa.Column("transfer", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("metadata_json", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_evidence_concept_time", "evidence", ["concept_id", "timestamp"], unique=False
    )
    op.create_index("idx_evidence_goal_time", "evidence", ["goal_id", "timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_evidence_goal_time", table_name="evidence")
    op.drop_index("idx_evidence_concept_time", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("evaluations")
    op.drop_table("exercise_concepts")
    op.drop_table("exercise_attempts")
    op.drop_table("activities")
    op.drop_table("skill_concepts")
    op.drop_table("sessions")
    op.drop_index("idx_reviews_schedule", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("idx_mistakes_concept", table_name="mistakes")
    op.drop_table("mistakes")
    op.drop_table("goal_concepts")
    op.drop_table("exercises")
    op.drop_table("concept_relations")
    op.drop_index("idx_vault_files_hash", table_name="vault_files")
    op.drop_table("vault_files")
    op.drop_table("skills")
    op.drop_table("goals")
    op.drop_index("idx_concepts_next_review", table_name="concepts")
    op.drop_table("concepts")
    op.drop_table("ai_runs")
    # ### end Alembic commands ###
